#!/bin/bash

args=""
if ! echo "$@" | grep -q "\(^version\|^completion\|^config\|^generate yaml\|^generate provider\|^help\)"; then
	args="--kubeconfig=${SNAP_DATA}/credentials/client.config"
fi

"${SNAP_COMMON}/plugins/.clusterctl" --config "${SNAP_COMMON}/clusterctl.yaml" ${args} "$@"
